blog/urls.py
from django.urls import path
from blog import views
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='index'),
    path('<int:pid>', views.blog_single, name='single'),
    path('category/<str:cat_name>', views.blog, name='category'),
    path('tag/<str:tag_name>', views.blog, name='tag'),
    path('author/<str:author_username>', views.blog, name='author'),
    path('search', views.blog_search, name='search'),  
    path('rss/feed/', LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.contrib.auth import views as auth_views
from accounts.urls import views as accounts_views

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),  
    # path('__debug__/', include('debug_toolbar.urls')),
    path('captcha/', include('captcha.urls')),
    path('auth_login', accounts_views.login, name='auth_login'),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('newsletter', views.newsletter, name='newsletter'),

]

website/models.py
from unicodedata import name
from django.db import models

class Contact(models.Model):
  name = models.CharField(max_length=255)
  email = models.EmailField()
  subject = models.CharField(max_length=255, blank=True)
  message = models.TextField()
  created_date = models.DateTimeField(auto_now_add=True)
  updated_date = models.DateTimeField(auto_now=True)


class Newsletter(models.Model):
  email = models.EmailField()

  def __str__(self):
      return self.email

website/forms.py
from django import forms
from website.models import Contact, Newsletter
from captcha.fields import CaptchaField

class NameForm(forms.Form):
    name = forms.CharField(max_length=255)


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Contact
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['subject'].required = False


class NewsletterForm(forms.ModelForm):

    class Meta():
        model = Newsletter
        fields = '__all__'

website/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from website.forms import ContactForm, NewsletterForm
from django.contrib import messages

def index(request):
  return render(request, 'website/index.html')

def about(request):
  return render(request, 'website/about.html')

def contact(request):
  if request.method == 'POST':
    form = ContactForm(request.POST)
    if form.is_valid():
      newform = form.save(commit=False)
      newform.name = 'anonymous'
      newform.save()
      messages.success(request, 'your ticket submited successfully.')
    else:
      messages.error(request, "your ticket didn't submited.")
  else:
    form = ContactForm()
  return render(request, 'website/contact.html', {'form': form})


def newsletter(request):
  if request.method == 'POST':
    form = NewsletterForm(request.POST)
    if form.is_valid():
      form.save()
      messages.success(request, 'your ticket submited successfully.')
      return HttpResponseRedirect('/')
  messages.error(request, "your ticket didn't submited.")
  return HttpResponseRedirect('/')

templates/website/about.html
{% extends 'base.html' %} {% load static %} {% block container %}
<!-- start banner Area -->
<section class="about-banner relative">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">About Us</h1>
        <p class="text-white link-nav">
          <a href="index.html">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="about.html"> About Us</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start about-info Area -->
<section class="about-info-area section-gap">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 info-left">
        <img class="img-fluid" src="{% static 'img/about/info-img.jpg' %}" alt="" />
      </div>
      <div class="col-lg-6 info-right">
        <h6>About Us</h6>
        <h1>Who We Are?</h1>
        <p>
          Here, I focus on a range of items and features that we use in life
          without giving them a second thought. such as Coca Cola. Dolor sit
          amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
          ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
          nostrud exercitation ullamco.
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End about-info Area -->

<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Other issues we can help you with</h1>
          <p>
            We all live in an age that belongs to the young at heart. Life that
            is.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Rent a Car</h4>
          </a>
          <p>
            The preservation of human life is the ultimate value, a pillar of
            ethics and the foundation.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Cruise Booking</h4>
          </a>
          <p>
            I was always somebody who felt quite sorry for myself, what I had
            not got compared.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>To Do List</h4>
          </a>
          <p>
            The following article covers a topic that has recently moved to
            center stage–at least it seems.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Food Features</h4>
          </a>
          <p>
            There are many kinds of narratives and organizing principles.
            Science is driven by evidence.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End other-issue Area -->
{% endblock %}

templates/website/contact.html
{% extends 'base.html' %} {% load static %} {% block container %}
<!-- start banner Area -->
<section class="relative about-banner">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">Contact Us</h1>
        <p class="text-white link-nav">
          <a href="index.html">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="contact.html"> Contact Us</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start contact-page Area -->
<section class="contact-page-area section-gap">
  <div class="container">
    <div class="row">
      <div class="map-wrap" style="width: 100%; height: 445px" id="map"></div>
      <div class="col-lg-4 d-flex flex-column address-wrap">
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-home"></span>
          </div>
          <div class="contact-details">
            <h5>Binghamton, New York</h5>
            <p>4343 Hinkle Deegan Lake Road</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-phone-handset"></span>
          </div>
          <div class="contact-details">
            <h5>00 (958) 9865 562</h5>
            <p>Mon to Fri 9am to 6 pm</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-envelope"></span>
          </div>
          <div class="contact-details">
            <h5>support@colorlib.com</h5>
            <p>Send us your query anytime!</p>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <form class="form-area contact-form text-right" action="{% url 'website:contact' %}" method="post">
          {% csrf_token %}
          <div class="row">
            <div class="col-lg-6 form-group">
              <input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control" required=""
                type="text" />

              <input name="email" placeholder="Enter email address"
                pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter email address'" class="common-input mb-20 form-control" required=""
                type="email" />

              <input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control" type="text" />
                  
            </div>
            <div class="col-lg-6 form-group">
              <textarea class="common-textarea form-control" name="message" placeholder="Enter Messege"
                onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'" required=""></textarea>
            </div>
       
            <div class="col-lg-12">
              <div calss="common-input mb-20 form-control pb-3" >
                {{form.captcha}}
              </div>  
              <div class="alert-msg" style="text-align: left"></div>
              <button type="submit" class="genric-btn primary" style="float: right">
                Send Message
              </button>
            </div>
          </div>
        </form>
        
        {% if form.errors %}
        <div class="alert alert-error">
          <h4>Please fix the following errors</h4>
          <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li>{{ error|escape }}</li>
            {% endfor %}
            {% endif %}
            {% endfor %}
          </ul>
          {% if form.non_field_errors %}
          {{ form.non_field_errors }}
          {% endif %}
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</section>
<!-- End contact-page Area -->
{% endblock %}

templates/website/index.html
{% extends 'base.html' %}
{% load static %}
{% load website_tags %}
{% block container %}
<!-- start banner Area -->
<section class="banner-area relative">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row fullscreen align-items-center justify-content-between">
      <div class="col-lg-6 col-md-6 banner-left">
        <h6 class="text-white">Away from monotonous life</h6>
        <h1 class="text-white">Magical Travel</h1>
        <p class="text-white">
          If you are looking at blank cassettes on the web, you may be very
          confused at the difference in price. You may see some for as low as
          $.17 each.
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start popular-destination Area -->
<section class="popular-destination-area pt-40 pb-40">
</section>
<!-- End popular-destination Area -->

<!-- Start home-about Area -->
<section class="home-about-area">
  <div class="container-fluid">
    <div class="row align-items-center justify-content-end">
      <div class="col-lg-6 col-md-12 home-about-left">
        <p class="home-about-custom">
          Travel makes people better versions of themselves. When you learn more about the world and the people in it, push your boundaries, and try new things, you become a more open, outgoing, and awesome person. All the people I’ve known who have traveled are better because of it.
          <br><br>
          With all the ways a trip can make you more of an awesome person, there’s no reason why you shouldn’t be planning your next adventure now — whether it’s around the world or just a two-week vacation close to home.
        </p>
      </div>
      <div class="col-lg-6 col-md-12 home-about-right no-padding">
        <img class="img-fluid" src="{% static 'img/about-img.jpg' %}" alt="" />
      </div>
    </div>
  </div>
</section>
<!-- End home-about Area -->

<!-- Start blog Area -->
{% latestpost %}
<!-- End recent-blog Area -->
{% endblock %}

templates/website/latest-blog.html
{% load static %}
<!-- Start blog Area -->
<section class="recent-blog-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-60 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Latest from Our Blog</h1>
          <p>
            With the exception of Nietzsche, no other madman has contributed so
            much to human sanity as has.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="active-recent-blog-carusel owl-carousel owl-theme owl-loaded">
        <div class="owl-stage-outer">
          <div class="owlstage latest-posts">
            {% for post in posts %}
            <div class="owl-item latest-post">
              <div class="single-recent-blog-post item">
                <div class="thumb">
                  <img class="img-fluid" src="{{post.image.url}}" alt="" />
                </div>
                <div class="details">
                  <div class="tags">
                    <ul>
                      {% for cat in post.category.all %}
                      <li>
                        <a href="{% url 'blog:category' cat_name=cat.name %}">
                          {{cat.name}}
                        </a>
                      </li>
                      {% endfor %}
                    </ul>
                  </div>
                  <a href="{% url 'blog:single' pid=post.id %}"
                    ><h4 class="title">{{post.title}}</h4></a
                  >
                  <p>{{post.content|safe|truncatechars_html:30}}</p>
                  <h6 class="date">{{post.published_date|date:"d M Y"}}</h6>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End recent-blog Area -->

templates/website/messages.html
{% load static %}
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" style=" position: fixed;  top: 50%;  left: 50%;  transform: translate(-50%, -50%);  width: 50%;">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="True">&times;</span>
      </button>
      {{ message }}
    </div>
{% endfor %}