accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # login 
    path('login/', views.login, name='login'),
    # logout
    path('logout', views.logout, name='logout'),
    # signup
    path('signup', views.signup, name='signup'),
]

blog/urls.py
from django.urls import path
from blog import views
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='index'),
    path('<int:pid>', views.blog_single, name='single'),
    path('category/<str:cat_name>', views.blog, name='category'),
    path('tag/<str:tag_name>', views.blog, name='tag'),
    path('author/<str:author_username>', views.blog, name='author'),
    path('search', views.blog_search, name='search'),  
    path('rss/feed/', LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.contrib.auth import views as auth_views
from accounts.urls import views as accounts_views

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),  
    # path('__debug__/', include('debug_toolbar.urls')),
    path('captcha/', include('captcha.urls')),
    path('auth_login', accounts_views.login, name='auth_login'),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('newsletter', views.newsletter, name='newsletter'),

]

templates/base-auth.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}style.css" />

</head>

<body>
    <div id="header">
    {% block header %}
    <a href="{% url 'website:index' %}">{% trans "Home" %}</a> | 

    {% if user.is_authenticated %}
        {% trans "Logged in" %}: {{ user.username }} 
        (<a href="{% url 'accounts:logout' %}">{% trans "Log out" %}</a> | 
        <a href="{% url 'reset_password' %}">{% trans "Change password" %}</a>)
    {% else %}
       <a href="{% url 'accounts:login' %}">{% trans "Log in" %}</a>
    {% endif %}
    <hr />
    {% endblock %}
    </div>

    <div id="content">
    {% block content %}{% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
        <hr />
    {% endblock %}
    </div>
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
  <head>
    <!-- Mobile Specific Meta -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}" />
    <!-- Author Meta -->
    <meta name="author" content="colorlib" />
    <!-- Meta Description -->
    <meta name="description" content="" />
    <!-- Meta Keyword -->
    <meta name="keywords" content="" />
    <!-- meta character set -->
    <meta charset="UTF-8" />
    <!-- Site Title -->
    <title>Travel</title>

    <link
      href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700"
      rel="stylesheet"
    />
    <!--
			CSS
			============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>

  <body>
    {% block container %} {% endblock %}
    <header id="header">
      <div class="header-top"></div>
      <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
          <div id="header-container">
            <div id="logo">
              <a href="{% url 'website:index' %}"
                ><img src="{% static 'img/logo.png' %}" alt="" title=""
              /></a>
            </div>
            <nav id="nav-menu-container">
              <ul class="nav-menu">
                <li><a href="{% url 'website:index' %}">Home</a></li>
                <li><a href="{% url 'website:about' %}">About</a></li>
                <li><a href="{% url 'blog:index' %}">Blog</a></li>
                <li><a href="{% url 'website:contact' %}">Contact</a></li>
              </ul>
            </nav>
            <!-- #nav-menu-container -->
          </div>
          {% if not user.is_authenticated %}
          <nav id="nav-menu-container2">
            <ul class="nav-menu justify-content-end" style="margin-right: 15px">
              <li><a href="{% url 'accounts:login' %}">Login</a></li>
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
            </ul>
          </nav>
          <!-- #nav-menu-container2 -->
          {% else %}
          <nav id="nav-menu-container2">
            <ul class="nav-menu justify-content-end" style="margin-right: 15px">
              <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
            </ul>
          </nav>
          <!-- #nav-menu-container2 -->
          {% endif %}
        </div>
      </div>
    </header>
    <!-- #header -->

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Agency</h6>
              <p>
                The world has become so fast paced that people don’t want to
                stand by reading a page of information, they would much rather
                look at a presentation and understand the message. It has come
                to a point
              </p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Navigation Links</h6>
              <div class="row">
                <div class="col">
                  <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Feature</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Portfolio</a></li>
                  </ul>
                </div>
                <div class="col">
                  <ul>
                    <li><a href="#">Team</a></li>
                    <li><a href="#">Pricing</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Newsletter</h6>
              <p>
                For business professionals caught between high OEM price and
                mediocre print and graphic output.
              </p>
              <div>
                <form
                  action="{% url 'website:newsletter' %}"
                  method="post"
                  class="subscription relative"
                >
                  {% csrf_token %}
                  <div class="input-group d-flex flex-row">
                    <input
                      name="email"
                      placeholder="Email Address"
                      onfocus="this.placeholder = ''"
                      onblur="this.placeholder = 'Email Address '"
                      required=""
                      type="email"
                      pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"
                      title="Invalid email address"
                    />
                    <button type="submit" class="btn bb-btn">
                      <span class="lnr lnr-location"></span>
                    </button>
                  </div>
                  <div class="mt-10 info"></div>
                </form>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget mail-chimp">
              <h6 class="mb-20">InstaFeed</h6>
              <ul class="instafeed d-flex flex-wrap">
                <li><img src="{% static 'img/i1.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i2.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i3.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i4.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i5.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i6.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i7.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i8.jpg' %}" alt="" /></li>
              </ul>
            </div>
          </div>
        </div>

        <div
          class="row footer-bottom d-flex justify-content-between align-items-center"
        >
          <p class="col-lg-8 col-sm-12 footer-text m-0">
            Copyright &copy;
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved
          </p>
          <div class="col-lg-4 col-sm-12 footer-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
          </div>
        </div>
      </div>
    </footer>

    {% include 'website/messages.html' %}

    <!-- End footer Area -->

    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/hoverIntent.js' %}"></script>
    <script src="{% static 'js/superfish.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends "base-auth.html" %}
{% load i18n %}

{% block content %}
Index page
{% endblock %}